import pickle
import pandas as pd
df0 = pickle.load(open("data_1.pickle",'rb'))
df0.columns = [str(c) for c in df0.columns]
df0["index"] = df0.index
size__before = df0.shape[0]
df0 = df0[df0.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and ( 0 if pd.isnull(row["age"]) else row["age"]) == 22 and ( 0 if pd.isnull(row["gender"]) else row["gender"]) == 'Female' and ( 0 if pd.isnull(row["race"]) else row["race"]) == 'WhiteOnly' and ( 0 if pd.isnull(row["ethnicity"]) else row["ethnicity"]) == 'Non-Hispanic' and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row[" 0 if pd.isnull(x["age"]) else x["age"]"]] if row[" 0 if pd.isnull(x["age"]) else x["age"]"] in ["Female","Male"] else row[" 0 if pd.isnull(x["age"]) else x["age"]"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
size__after = df0.shape[0]
print("Input data_1.pickle filter reduce data from {} rows to {} rows".format(size__before, size__after))
df0_0 = df0[df0.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and ( 0 if pd.isnull(row["age"]) else row["age"]) == 22 and ( 0 if pd.isnull(row["gender"]) else row["gender"]) == 'Female' and ( 0 if pd.isnull(row["race"]) else row["race"]) == 'WhiteOnly' and ( 0 if pd.isnull(row["ethnicity"]) else row["ethnicity"]) == 'Non-Hispanic' and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row[" 0 if pd.isnull(x["age"]) else x["age"]"]] if row[" 0 if pd.isnull(x["age"]) else x["age"]"] in ["Female","Male"] else row[" 0 if pd.isnull(x["age"]) else x["age"]"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df1=df0_0
df1["age"] = df1["age"].fillna(value=0)
df1_0 = df1[df1.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and (row['age'] == 22) and ( 0 if pd.isnull(row["gender"]) else row["gender"]) == 'Female' and ( 0 if pd.isnull(row["race"]) else row["race"]) == 'WhiteOnly' and ( 0 if pd.isnull(row["ethnicity"]) else row["ethnicity"]) == 'Non-Hispanic' and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row[" fill_value if pd.isnull(x[col]) else x[col]"]] if row[" fill_value if pd.isnull(x[col]) else x[col]"] in ["Female","Male"] else row[" fill_value if pd.isnull(x[col]) else x[col]"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df2=df1_0
df2["gender"] = df2["gender"].fillna(value=0)
df2_0 = df2[df2.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and (row['age'] == 22) and (row['gender'] == 'Female') and ( 0 if pd.isnull(row["race"]) else row["race"]) == 'WhiteOnly' and ( 0 if pd.isnull(row["ethnicity"]) else row["ethnicity"]) == 'Non-Hispanic' and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df3=df2_0
df3["race"] = df3["race"].fillna(value=0)
df3_0 = df3[df3.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and ( 0 if pd.isnull(row["ethnicity"]) else row["ethnicity"]) == 'Non-Hispanic' and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df4=df3_0
df4["ethnicity"] = df4["ethnicity"].fillna(value=0)
df4_0 = df4[df4.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and ( 0 if pd.isnull(row["employment_status"]) else row["employment_status"]) == 'Working' and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row[' 0 if pd.isnull(x["employment_status"]) else x["employment_status"]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df5=df4_0
df5["employment_status"] = df5["employment_status"].fillna(value=0)
df5_0 = df5[df5.apply(lambda row: ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) > 0 and (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and ( 0 if pd.isnull(row["hours_worked_per_week"]) else row["hours_worked_per_week"]) == 40.0 and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row[' fill_value if pd.isnull(x[col]) else x[col]'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df6=df5_0
df6["hours_worked_per_week"] = df6["hours_worked_per_week"].fillna(value=0)
df6_0 = df6[df6.apply(lambda row: (row['hours_worked_per_week'] > 0) and (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and ( 0 if pd.isnull(row["earnings_per_week"]) else row["earnings_per_week"]) == 328.0 and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row['hours_worked_per_week'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df7=df6_0
df7["earnings_per_week"] = df7["earnings_per_week"].fillna(value=0)
df7_0 = df7[df7.apply(lambda row: (row['hours_worked_per_week'] > 0) and (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and (row['earnings_per_week'] == 328.0) and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row['hours_worked_per_week'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df8 = df7_0[df7_0.apply(lambda row: row['hours_worked_per_week'] > 0, axis=1)]
df8_0 = df8[df8.apply(lambda row: (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and (row['earnings_per_week'] == 328.0) and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row['hours_worked_per_week'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df9 = df8_0.copy()
df9_0 = df9[df9.apply(lambda row: (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and (row['earnings_per_week'] == 328.0) and (row['index'] == '9_110826_10565') and ( ({ "Female":1,"Male":0 }[row["gender"]] if row["gender"] in ["Female","Male"] else row["gender"])) == 1 and ( 1 if row['hours_worked_per_week'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df10 = df9_0
df10["female"] = df10.apply(lambda xxx__: ({ "Female":1,"Male":0 }[xxx__["gender"]] if xxx__["gender"] in ["Female","Male"] else xxx__["gender"]), axis=1)
df10_0 = df10[df10.apply(lambda row: (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and (row['earnings_per_week'] == 328.0) and (row['index'] == '9_110826_10565') and (row['female'] == 1) and ( 1 if row['hours_worked_per_week'] > 38.8 else 0) == 1 and (row['index'] == '9_110826_10565'), axis=1)]
df11 = df10_0
df11["person_hard_worker"] = df11.apply(lambda xxx__: 1 if xxx__['hours_worked_per_week'] > 38.8 else 0, axis=1)
df11_0 = df11[df11.apply(lambda row: (row['age'] == 22) and (row['gender'] == 'Female') and (row['race'] == 'WhiteOnly') and (row['ethnicity'] == 'Non-Hispanic') and (row['employment_status'] == 'Working') and (row['hours_worked_per_week'] == 40.0) and (row['earnings_per_week'] == 328.0) and (row['index'] == '9_110826_10565') and (row['female'] == 1) and (row['person_hard_worker'] == 1) and (row['index'] == '9_110826_10565'), axis=1)]
pickle.dump(df11, open('temp//result_after_pushdown.p', 'wb'))