import pickle
# df0 = pickle.load(open("data_0.pickle",'rb'))
# df0.columns = [str(c) for c in df0.columns]
# df0["index"] = df0.index
# df1 = df0[df0['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA']
# df2 = df1[df1['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']
# df3 = df2.drop(columns=["FW_INFO_EDUCATION_OTHER","DECISION_ELAPSED_YEARS","JOB_INFO_EDUCATION_OTHER","DECISION_DATE_MONTH","AGENT_FIRM_NAME","WAGE_OFFER_UNIT_OF_PAY_9089","FOREIGN_WORKER_INFO_CITY","DECISION_DATE","EMPLOYER_NAME","CASE_RECEIVED_DATE","JOB_INFO_JOB_TITLE","FW_INFO_POSTAL_CODE","AGENT_CITY","CASE_NUMBER","PW_SOC_CODE","Unnamed: 0","Unnamed: 1","FW_INFO_BIRTH_COUNTRY","AGENT_STATE","EMPLOYER_CITY","DECISION_DATE_YEAR","JOB_INFO_WORK_CITY","JOB_INFO_WORK_POSTAL_CODE","PW_SOC_TITLE","PW_AMOUNT_9089","JOB_INFO_EDUCATION","CASE_RECEIVED_DATE_YEAR","FOREIGN_WORKER_INFO_STATE","JOB_INFO_WORK_STATE"])
# df4 = df3
# df4["EMPLOYER_STATES"] = df4.apply(lambda xxx__: {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[xxx__['EMPLOYER_STATE']] \
#     if xxx__['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else xxx__['EMPLOYER_STATE'], axis=1)
# df5 = df4.dropna(subset=["CASE_STATUS","DECISION_ELAPSED_DAYS","EMPLOYER_POSTAL_CODE","EMPLOYER_STATE","EMPLOYER_NUM_EMPLOYEES","WAGE_OFFER_FROM_9089","COUNTRY_OF_CITIZENSHIP","CLASS_OF_ADMISSION","FOREIGN_WORKER_INFO_EDUCATION","CASE_RECEIVED_DATE_MONTH","EMPLOYER_STATES"])
# df6 = df5.drop(columns=["CASE_STATUS"])
# final_output = df6[df6['EMPLOYER_NUM_EMPLOYEES'] == 5]
# print(final_output)
# pickle.dump(final_output, open('temp//result_pred_on_output.p', 'wb'))


# df0 = pickle.load(open("data_0.pickle",'rb'))
# df0.columns = [str(c) for c in df0.columns]
# df0["index"] = df0.index
# df0 = df0[(df0['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA') & ((df0['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year') & ((((((((((((df0['CASE_STATUS'].notnull()) | (df0['DECISION_ELAPSED_DAYS'].notnull())) | (df0['EMPLOYER_POSTAL_CODE'].notnull())) | (df0['EMPLOYER_STATE'].notnull())) | (df0['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df0['WAGE_OFFER_FROM_9089'].notnull())) | (df0['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df0['CLASS_OF_ADMISSION'].notnull())) | (df0['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df0['CASE_RECEIVED_DATE_MONTH'].notnull())) | (( {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[df0['EMPLOYER_STATE']] \
#     if df0['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else df0['EMPLOYER_STATE']).notnull())) & (df0['EMPLOYER_NUM_EMPLOYEES'] == 5)))]
# df0_0 = df0[(df0['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA') & ((df0['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year') & ((((((((((((df0['CASE_STATUS'].notnull()) | (df0['DECISION_ELAPSED_DAYS'].notnull())) | (df0['EMPLOYER_POSTAL_CODE'].notnull())) | (df0['EMPLOYER_STATE'].notnull())) | (df0['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df0['WAGE_OFFER_FROM_9089'].notnull())) | (df0['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df0['CLASS_OF_ADMISSION'].notnull())) | (df0['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df0['CASE_RECEIVED_DATE_MONTH'].notnull())) | (( {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[df0['EMPLOYER_STATE']] \
#     if df0['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else df0['EMPLOYER_STATE']).notnull())) & (df0['EMPLOYER_NUM_EMPLOYEES'] == 5)))]
# df1 = df0_0[df0_0['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA']
# df1_0 = df1[(df1['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year') & ((((((((((((df1['CASE_STATUS'].notnull()) | (df1['DECISION_ELAPSED_DAYS'].notnull())) | (df1['EMPLOYER_POSTAL_CODE'].notnull())) | (df1['EMPLOYER_STATE'].notnull())) | (df1['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df1['WAGE_OFFER_FROM_9089'].notnull())) | (df1['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df1['CLASS_OF_ADMISSION'].notnull())) | (df1['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df1['CASE_RECEIVED_DATE_MONTH'].notnull())) | (( {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[df1['EMPLOYER_STATE']] \
#     if df1['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else df1['EMPLOYER_STATE']).notnull())) & (df1['EMPLOYER_NUM_EMPLOYEES'] == 5))]
# df2 = df1_0[df1_0['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year']
# df2_0 = df2[(((((((((((df2['CASE_STATUS'].notnull()) | (df2['DECISION_ELAPSED_DAYS'].notnull())) | (df2['EMPLOYER_POSTAL_CODE'].notnull())) | (df2['EMPLOYER_STATE'].notnull())) | (df2['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df2['WAGE_OFFER_FROM_9089'].notnull())) | (df2['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df2['CLASS_OF_ADMISSION'].notnull())) | (df2['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df2['CASE_RECEIVED_DATE_MONTH'].notnull())) | (( {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[df2['EMPLOYER_STATE']] \
#     if df2['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else df2['EMPLOYER_STATE']).notnull())) & (df2['EMPLOYER_NUM_EMPLOYEES'] == 5)]
# df3 = df2_0.drop(columns=["FW_INFO_EDUCATION_OTHER","DECISION_ELAPSED_YEARS","JOB_INFO_EDUCATION_OTHER","DECISION_DATE_MONTH","AGENT_FIRM_NAME","WAGE_OFFER_UNIT_OF_PAY_9089","FOREIGN_WORKER_INFO_CITY","DECISION_DATE","EMPLOYER_NAME","CASE_RECEIVED_DATE","JOB_INFO_JOB_TITLE","FW_INFO_POSTAL_CODE","AGENT_CITY","CASE_NUMBER","PW_SOC_CODE","Unnamed: 0","Unnamed: 1","FW_INFO_BIRTH_COUNTRY","AGENT_STATE","EMPLOYER_CITY","DECISION_DATE_YEAR","JOB_INFO_WORK_CITY","JOB_INFO_WORK_POSTAL_CODE","PW_SOC_TITLE","PW_AMOUNT_9089","JOB_INFO_EDUCATION","CASE_RECEIVED_DATE_YEAR","FOREIGN_WORKER_INFO_STATE","JOB_INFO_WORK_STATE"])
# df3_0 = df3[(((((((((((df3['CASE_STATUS'].notnull()) | (df3['DECISION_ELAPSED_DAYS'].notnull())) | (df3['EMPLOYER_POSTAL_CODE'].notnull())) | (df3['EMPLOYER_STATE'].notnull())) | (df3['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df3['WAGE_OFFER_FROM_9089'].notnull())) | (df3['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df3['CLASS_OF_ADMISSION'].notnull())) | (df3['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df3['CASE_RECEIVED_DATE_MONTH'].notnull())) | (( {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[df3['EMPLOYER_STATE']] \
#     if df3['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else df3['EMPLOYER_STATE']).notnull())) & (df3['EMPLOYER_NUM_EMPLOYEES'] == 5)]
# df4 = df3_0
# df4["EMPLOYER_STATES"] = df4.apply(lambda xxx__: {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[xxx__['EMPLOYER_STATE']] \
#     if xxx__['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else xxx__['EMPLOYER_STATE'], axis=1)
# df4_0 = df4[(((((((((((df4['CASE_STATUS'].notnull()) | (df4['DECISION_ELAPSED_DAYS'].notnull())) | (df4['EMPLOYER_POSTAL_CODE'].notnull())) | (df4['EMPLOYER_STATE'].notnull())) | (df4['EMPLOYER_NUM_EMPLOYEES'].notnull())) | (df4['WAGE_OFFER_FROM_9089'].notnull())) | (df4['COUNTRY_OF_CITIZENSHIP'].notnull())) | (df4['CLASS_OF_ADMISSION'].notnull())) | (df4['FOREIGN_WORKER_INFO_EDUCATION'].notnull())) | (df4['CASE_RECEIVED_DATE_MONTH'].notnull())) | (df4['EMPLOYER_STATES'].notnull())) & (df4['EMPLOYER_NUM_EMPLOYEES'] == 5)]
# df5 = df4_0.dropna(subset=["CASE_STATUS","DECISION_ELAPSED_DAYS","EMPLOYER_POSTAL_CODE","EMPLOYER_STATE","EMPLOYER_NUM_EMPLOYEES","WAGE_OFFER_FROM_9089","COUNTRY_OF_CITIZENSHIP","CLASS_OF_ADMISSION","FOREIGN_WORKER_INFO_EDUCATION","CASE_RECEIVED_DATE_MONTH","EMPLOYER_STATES"])
# df5_0 = df5[df5['EMPLOYER_NUM_EMPLOYEES'] == 5]
# df6 = df5_0.drop(columns=["CASE_STATUS"])
# df6_0 = df6[df6['EMPLOYER_NUM_EMPLOYEES'] == 5]
# pickle.dump(df6, open('temp//result_after_pushdown.p', 'wb'))
df0 = pickle.load(open("data_0.pickle",'rb'))
df0.columns = [str(c) for c in df0.columns]
df0["index"] = df0.index
df1 = df0[df0.apply(lambda row: row['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA', axis=1)]
df2 = df1[df1.apply(lambda row: row['WAGE_OFFER_UNIT_OF_PAY_9089'] == 'Year', axis=1)]
df3 = df2.drop(columns=["FW_INFO_EDUCATION_OTHER","DECISION_ELAPSED_YEARS","JOB_INFO_EDUCATION_OTHER","DECISION_DATE_MONTH","AGENT_FIRM_NAME","WAGE_OFFER_UNIT_OF_PAY_9089","FOREIGN_WORKER_INFO_CITY","DECISION_DATE","EMPLOYER_NAME","CASE_RECEIVED_DATE","JOB_INFO_JOB_TITLE","FW_INFO_POSTAL_CODE","AGENT_CITY","CASE_NUMBER","PW_SOC_CODE","Unnamed: 0","Unnamed: 1","FW_INFO_BIRTH_COUNTRY","AGENT_STATE","EMPLOYER_CITY","DECISION_DATE_YEAR","JOB_INFO_WORK_CITY","JOB_INFO_WORK_POSTAL_CODE","PW_SOC_TITLE","PW_AMOUNT_9089","JOB_INFO_EDUCATION","CASE_RECEIVED_DATE_YEAR","FOREIGN_WORKER_INFO_STATE","JOB_INFO_WORK_STATE"])
df4 = df3
df4["EMPLOYER_STATES"] = df4.apply(lambda xxx__: {'AL': 'ALABAMA', 'AK': 'ALASKA', 'AZ': 'ARIZONA', 'AR': 'ARKANSAS', 'CA': 'CALIFORNIA', 'CO': 'COLORADO', 'CT': 'CONNECTICUT', 'DE': 'DELAWARE', 'FL': 'FLORIDA', 'GA': 'GEORGIA', 'HI': 'HAWAII', 'ID': 'IDAHO', 'IL': 'ILLINOIS', 'IN': 'INDIANA', 'IA': 'IOWA', 'KS': 'KANSAS', 'KY': 'KENTUCKY', 'LA': 'LOUISIANA', 'ME': 'MAINE', 'MD': 'MARYLAND', 'MA': 'MASSACHUSETTS', 'MI': 'MICHIGAN', 'MN': 'MINNESOTA', 'MS': 'MISSISSIPPI', 'MO': 'MISSOURI', 'MT': 'MONTANA', 'NE': 'NEBRASKA', 'NV': 'NEVADA', 'NH': 'NEW HAMPSHIRE', 'NJ': 'NEW JERSEY', 'NM': 'NEW MEXICO', 'NY': 'NEW YORK', 'NC': 'NORTH CAROLINA', 'ND': 'NORTH DAKOTA', 'OH': 'OHIO', 'OK': 'OKLAHOMA', 'OR': 'OREGON', 'PA': 'PENNSYLVANIA', 'RI': 'RHODE ISLAND', 'SC': 'SOUTH CAROLINA', 'SD': 'SOUTH DAKOTA', 'TN': 'TENNESSEE', 'TX': 'TEXAS', 'UT': 'UTAH', 'VT': 'VERMONT', 'VA': 'VIRGINIA', 'WA': 'WASHINGTON', 'WV': 'WEST VIRGINIA', 'WI': 'WISCONSIN', 'WY': 'WYOMING'}[xxx__['EMPLOYER_STATE']]     if xxx__['EMPLOYER_STATE'] in ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] else xxx__['EMPLOYER_STATE'], axis=1)
df5 = df4.dropna(subset=["CASE_STATUS","DECISION_ELAPSED_DAYS","EMPLOYER_POSTAL_CODE","EMPLOYER_STATE","EMPLOYER_NUM_EMPLOYEES","WAGE_OFFER_FROM_9089","COUNTRY_OF_CITIZENSHIP","CLASS_OF_ADMISSION","FOREIGN_WORKER_INFO_EDUCATION","CASE_RECEIVED_DATE_MONTH","EMPLOYER_STATES"])
df6 = df5.drop(columns=["CASE_STATUS"])
final_output = df6[df6.apply(lambda row: (((((row['DECISION_ELAPSED_DAYS'] == 98) and (row['EMPLOYER_STATE'] == 'MA')) and (row['EMPLOYER_POSTAL_CODE'] == '01810')) and (row['EMPLOYER_NUM_EMPLOYEES'] > 5672.0)) and (row['WAGE_OFFER_FROM_9089'] <= 77376.0)) and (row['COUNTRY_OF_CITIZENSHIP'] == 'SOUTH KOREA'), axis=1)]
print(final_output)
pickle.dump(final_output, open('temp//result_pred_on_output.p', 'wb'))